# kis_devlp.yaml

# 실전 투자 계정 설정
my_app: "PS37wzsl8l576b6HpO0g5GulicDXoUvPPMbt"
my_sec: "alUamTBWWhB72dQ8j5i4CrWdB0Vf28SCokiq0OsveOGRrooFb9FT5eHoaMWNiSSVy3Yfnr+gnwkGdVmkSgt7YBjlx/dw/RJa2coNjYPItEVuVCDvo9xJyuJG4OrCoIvPdBoGW7ciiZ/FSKC7pqBZk/soZY1tGVsbWbxSfW7/NtnzJVZiQ2o="
my_acct_stock: "46206968"  # 실전 계좌번호 (8자리)
my_acct_future: "46206968"  # 실전 선물옵션 계좌번호 (8자리)

# 모의 투자 계정 설정
paper_app: "PSV43n2hnrCiDhx12R92auQzIueBBV09cJXl"
paper_sec: "Rx/+dz+C/OlfWqsf+AuR4rexARNFqNjQHuUOS5hpefUnqRrZ1cZNnFCdUbTr+5ptt8xFFKte9QS5vhZX9i4HyVs3sEoPWpVlhkiWclJGz3bNwHuSNbQep8pQ/ggUX/jEP1hXu3uZUMdDF+ljp7C1+1aeTLR2Bpk+0tsLMW76DdFrlhg9XhY="
my_paper_stock: "50137721"  # 모의 계좌번호 (8자리)
my_paper_future: "60032600"  # 모의 선물옵션 계좌번호 (8자리)

# 실전 및 모의 도메인 설정
prod: "https://openapi.koreainvestment.com:9443"
vps: "https://openapivts.koreainvestment.com:29443"

# 기타 설정
my_prod: "01"  # 기본 계좌상품코드 (예: 주식투자, 위탁계좌)
my_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
