FROM python:3.11-slim

# 기본 패키지 설치
RUN apt-get update && apt-get install -y gcc libpq-dev curl

# 작업 디렉토리 설정
WORKDIR /app

# 코드 복사
COPY ./trading /app/trading

# 필요한 파이썬 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# KIS 인증을 위한 토큰 파일/환경파일 등 필요한 경우 볼륨 또는 COPY 필요

# 실행
CMD ["python", "trading/trading.py"]
