# Generated by Django 5.2.1 on 2025-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(db_index=True)),
                ('Ticker', models.CharField(db_index=True, max_length=20)),
                ('Open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('High', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Volume', models.BigIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Date', 'Ticker'), name='unique_trade_per_day')],
            },
        ),
    ]
