# Generated by Django 5.2.1 on 2025-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_REWARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAPE', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Mean Absolute Percentage Error')),
                ('MAE', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Mean Absolute Error')),
                ('RMSE', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Root Mean Square Error')),
                ('R2', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='R-Squared')),
                ('REWARD', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Reward')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
            ],
        ),
    ]
